version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always

  odoo:
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
